### ISSUE TITLE
0.5 MNX  that goes to the minexbank reserve in not enforced in the consensus rules 

### ISSUE THREAD

**Issue by maxocoin** [minexcoin/minexcoin#12]
There are some miners that are not sending the .5 MNX from each block to the minexbank reserves  and they can get away with it because this is not enforced on the consensus rules, undermining the long term sustainability of the Minexbank 

For example, look at the transaction 
http://minexexplorer.com/?r=explorer/block&hash=000000429d2249251b2027ed1b678538f1bd5f0530d5f2602e3b1aaccce91b5e

**Comment by DANA-Laboratory** [comment]
Looks like this address now pays for bank reserve.
But where is developers?

**Comment by wirwolf** [comment]
Hello. This error will be fixed in the new version. Now we are testing a new version with this fix

**Comment by minexworker** [comment]
This bug already fixed in new version which is not published due to changing of consensus.
We don't publish new codebase right now because of analyzing and collecting other bugs to reduce amount of releases.

**Comment by MinexRnD** [comment]
fix in https://github.com/minexcoin/minexcoin/tree/v1.2.0.0
