### ISSUE TITLE
Command line usage to show what system will support as max usage

### ISSUE THREAD

**Issue by darless** [minexcoin/minexcoin#38]
This is an improvement request.

When running `./mxminer` you can currently get CUDA information as well as opencl information. The documentation also shows examples, but what it doesn't show you is the ability to see what the max is for everything.

Perhaps this makes sense for benchmark to figure out what the system can do. Maybe another option to it? It would look at CPU cores, GPU type and specs and then show what it thinks is the most optimal.

**Comment by MinexRnD** [comment]
What is the soft mxminer ? We didn't make this one.
All CUDA applications work with our system are not belong to us.
