### ISSUE TITLE
Difficuty is too high...

### ISSUE THREAD

**Issue by jdevora** [minexcoin/minexcoin#4]
I don't know when the difficulty is adjusted, but the 2nd August is approaching and we are getting one block every 2 hours instead of every 3 minutes.

Is there a way to introduce an earlier difficulty adjustment?   
What about a readjustment when the block generation gets abobe the target * 100% for 3 blocks?

**Comment by maxocoin** [comment]
What about implementing something similar to the Bitcoin Cash Forking rule for adjust the difficulty?
https://bitcointalk.org/index.php?topic=2040221.0

>In case the MTP of the tip of the chain is 12h or more after the MTP 6 block before the tip, the proof of work target is increased by a quarter, or 25%, which corresponds to a difficulty reduction of 20% .
>
>RATIONALE: The hashrate supporting the chain is dependent on market price and hard to predict. In order >to make sure the chain remains viable no matter what difficulty needs to adjust down in case of abrupt >hashrate drop."

**Comment by gaissa** [comment]
The difficulty changes (<s>halves?</s>) every 960 blocks.

edit: It can increase or decrease depending on block time every 960 block. Any official info about this? Not that this really matters anymore.

**Comment by maxocoin** [comment]
Yep, it ajustes to a number that will create one block every 2 minutes 45 seconds

The huge problem we had  is already sorted thanks to 1000 hps that showed up over night...

**Comment by maxocoin** [comment]
After a user with lots of mining power left the network, we are having the same issue, just one of two blocks per hour.

Minexcoin needs a way to quickly decrease the difficulty if there is one hour of so without a block

**Comment by minexworker** [comment]
Difficulty is adjusted now. The offers were reviewed but not implemented now.

**Comment by maxocoin** [comment]
We already saw a few times what lots of hash power left the network and we started to create one block every  hour or two and needing to wait weeks for a new difficulty adjustment.

  For just "internal use" it didn't affect too much the the coin's credibility, but when we hit an exchange, if something similar happens, it will kill the coins't ability to attract new supporters. Imagine that someone wants to trade and the trade takes 12 hour to be confirmed :-(

**Comment by MinexRnD** [comment]
There is a pool which not developed by minexcoin team http://minexpool.nl/.
We are doing one now without fee for pool owner.
