### ISSUE TITLE
minexcoin-qt  compile issues

### ISSUE THREAD

**Issue by leifliddy** [minexcoin/minexcoin#5]
Followed the instructions listed in Builds/Linux.sh on a Ubuntu 16.04 system
After running:
./autogen.sh
./configure --prefix=/--disable-tests
make -j 8 

Compilation fails at:

In file included from ./pow.h:9:0,
                 from ./chain.h:11,
                 from ./txdb.h:11,
                 from ./test/test_bitcoin.h:11,
                 from test/bswap_tests.cpp:6:
./crypto/equihash.h:157:65: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 inline constexpr const size_t max(const size_t A, const size_t B) { return A > B ? A : B; }
                                                                 ^
make[2]: Leaving directory '/minexcoin/src'
Makefile:8999: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/minexcoin/src'
Makefile:687: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by leifliddy** [comment]
this is due to a typo in Builds/Linux.sh
./configure --prefix=/--disable-tests
should be
./configure --prefix=/ --disable-tests
**there should be a space between --prefix=/ and --disable-tests

I'll create a pull request for this file.

**Comment by wirwolf** [comment]
In next release we build in docker containers.
We fix this in build scenario. 
If you want compile coin in linux use this command

./autogen.sh
./configure --prefix=/ --disable-tests
make all -j 6 -i
