### ISSUE TITLE
No feedback while mining.

### ISSUE THREAD

**Issue by maxocoin** [minexcoin/minexcoin#6]
When you issue the command  generate X     if will just hang there and the only feedback you get that is actually doing something is the CPU load.

Could it be possible to print some value, from time to time (e.g. number of hashes tried in the last minute)  to give some feed back?

Could you add a   mining=true   or something  when you do the   getmininginfo    RPC call?

**Comment by minexworker** [comment]
It's not a priority task.
It may be made after all major features will be done if solo mining will be effective.
